services:
  app:
    container_name: flask-api-1
    privileged: true
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
